SELECT DISTINCT
       ?statement
       ?item ?name_en ?name_hi
       ?party ?party_name_en ?party_name_hi
       ?district ?district_name_en ?district_name_hi
       ?role ?role_en ?role_hi
       ?start ?end ?facebook
       ?role_superclass ?role_superclass_en ?role_superclass_hi
       ?org ?org_en ?org_hi ?org_jurisdiction
WHERE {
  VALUES ?role { wd:Q58943923 }
  BIND(?role AS ?specific_role) .
  BIND(wd:Q58944788 AS ?org) .
  OPTIONAL {
  ?org rdfs:label ?org_en
  FILTER(LANG(?org_en) = "en")
}

OPTIONAL {
  ?org rdfs:label ?org_hi
  FILTER(LANG(?org_hi) = "hi")
}

  OPTIONAL {
    ?org wdt:P1001 ?org_jurisdiction
  }
  ?item wdt:P31 wd:Q5 ;
        p:P39 ?statement .
  OPTIONAL {
  ?item rdfs:label ?name_en
  FILTER(LANG(?name_en) = "en")
}

OPTIONAL {
  ?item rdfs:label ?name_hi
  FILTER(LANG(?name_hi) = "hi")
}

  ?statement ps:P39 ?specific_role .
  OPTIONAL {
  ?role rdfs:label ?role_en
  FILTER(LANG(?role_en) = "en")
}

OPTIONAL {
  ?role rdfs:label ?role_hi
  FILTER(LANG(?role_hi) = "hi")
}

  OPTIONAL {
    VALUES ?superclass_type { wd:Q2285706 wd:Q30461 }
    ?role wdt:P279 ?role_superclass .
    ?role_superclass wdt:P279* ?superclass_type .
    OPTIONAL {
  ?role_superclass rdfs:label ?role_superclass_en
  FILTER(LANG(?role_superclass_en) = "en")
}

OPTIONAL {
  ?role_superclass rdfs:label ?role_superclass_hi
  FILTER(LANG(?role_superclass_hi) = "hi")
}

  }
  OPTIONAL { ?statement pq:P580 ?start }
  OPTIONAL { ?statement pq:P582 ?end }
  OPTIONAL {
    ?role p:P1001/ps:P1001 ?district .
    OPTIONAL {
  ?district rdfs:label ?district_name_en
  FILTER(LANG(?district_name_en) = "en")
}

OPTIONAL {
  ?district rdfs:label ?district_name_hi
  FILTER(LANG(?district_name_hi) = "hi")
}

  }
  BIND(COALESCE(?end, "9999-12-31T00:00:00Z"^^xsd:dateTime) AS ?end_or_sentinel)
  FILTER(?end_or_sentinel >= NOW())
  # Find any current party membership:
  OPTIONAL {
    ?item p:P102 ?party_statement .
    ?party_statement ps:P102 ?party .
    OPTIONAL {
  ?party rdfs:label ?party_name_en
  FILTER(LANG(?party_name_en) = "en")
}

OPTIONAL {
  ?party rdfs:label ?party_name_hi
  FILTER(LANG(?party_name_hi) = "hi")
}

    OPTIONAL { ?party_statement pq:P582 ?end_party }
    BIND(COALESCE(?end_party, "9999-12-31T00:00:00Z"^^xsd:dateTime) AS ?party_end_or_sentinel)
    FILTER(?party_end_or_sentinel >= NOW())
  }
  OPTIONAL { ?item wdt:P2013 ?facebook }
} ORDER BY ?item ?role ?district ?start ?end ?role_superclass ?party ?org
