#!/usr/bin/env python3

import argparse

from utils import get_names

parser = argparse.ArgumentParser(
    description='Add Hindi names to reconciled csv')

parser.add_argument('in_csv', metavar='INPUT_CSV')
parser.add_argument('out_csv', metavar='OUTPUT_CSV')

args = parser.parse_args()

get_names(args.in_csv, args.out_csv, 'hi')
